version: '3.6'
services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testcache
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
  redis:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"
    restart: always
  graphql-engine:
    image: hasura/graphql-engine:v1.3.2
    depends_on:
    - postgres
    ports:
    - "8080"
    restart: always
    network_mode: "host"
    environment:
      HASURA_COCA_TRIGGER_BASE_URL: http://localhost:8081/triggers
      HASURA_COCA_ACTION_BASE_URL: http://localhost:8081/actions
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@localhost:5432/testcache
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey